### ISSUE TITLE
babel 7 compatibility

### ISSUE THREAD

**Issue by formatlos** [adam-26/babel-plugin-react-intl-id-hash#5]
I've tried to use the plugin with babel 7 but I get the following error:

```
Module build failed: TypeError: Cannot read property 'imports' of undefined
    at isImportLocalName (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/babel-plugin-react-intl-id-hash/lib/index.js:53:41)
    at isReactIntlImport (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/babel-plugin-react-intl-id-hash/lib/index.js:107:8)
    at PluginPass.CallExpression (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/babel-plugin-react-intl-id-hash/lib/index.js:12:14)
    at newFn (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/context.js:135:18)
    at TraversalContext.visitSingle (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/context.js:94:19)
    at TraversalContext.visit (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/context.js:176:19)
    at Function.traverse.node (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/context.js:135:18)
    at TraversalContext.visitMultiple (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/context.js:89:17)
    at TraversalContext.visit (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/context.js:174:19)
    at Function.traverse.node (/Users/martin/Documents/Projects/moebelde-frontend/node_modules/@babel/traverse/lib/index.js:76:17)
```

**Comment by adam-26** [comment]
@formatlos, this plugin was written for Babel 6. If you submit a PR for Babel 7 support I’ll publish a new version
